- Add postup service file. - Moved macvlan config file to `<namespace>-macvlan.conf`. - Added more information in readme.

diff --git a/scripts/netns-helperctl b/scripts/netns-helperctl
--- a/scripts/netns-helperctl
+++ b/scripts/netns-helperctl
@@ -3,13 +3,6 @@
 NS=$1
 CMD=$2
 
-if [[ ! -f /etc/netns-helper/ns/$NS.conf ]]; then
-	echo "File /etc/netns-helper/ns/$NS.conf not found, exiting."
-	exit 1
-fi
-
-source /etc/netns-helper/ns/$NS.conf
-
 case $CMD in
 	netns)
 		
@@ -46,12 +39,15 @@ case $CMD in
 
 		case $3 in
 			create)
+				if [[ ! -f /etc/netns-helper/ns/$NS-macvlan.conf ]]; then
+					echo "File /etc/netns-helper/ns/$NS-macvlan.conf not found, exiting."
+					exit 1
+				fi
+				
+				source /etc/netns-helper/ns/$NS-macvlan.conf
+				
 				echo "Creating macvlan interface in $NS with $PARENT_IF."
 				echo "MAC address: $MAC"
-				
-				if [[ -f /etc/netns-helper/ns/$NS-macvlan.conf ]]; then
-					source /etc/netns-helper/ns/$NS-macvlan.conf
-				fi
 
 				# Setup macvlan interface and link it to parent interface.
 				ip link add nm_$NS link $PARENT_IF address $MAC type macvlan mode bridge
@@ -95,7 +91,16 @@ case $CMD in
 		esac
 
 		;;
-
+		
+	postup)
+		
+		if [[ -x /etc/netns-helper/ns/$NS-postup ]]; then
+			/etc/netns-helper/ns/$NS-postup
+			exit $?
+		fi
+		
+		;;
+		
 	*)
 		echo "Wrong command."
 		exit 1
